version: '3'

services:
  backend:
    image: neper:backend
    build:
      context: ./backend/
      dockerfile: ../Dockerfile.dev.backend
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
