FROM alpine:3

RUN apk add --update --no-cache\
    make\
    nodejs\
    yarn

WORKDIR /data

COPY ./frontend/package.json ./frontend/package.json

RUN cd ./frontend && yarn install

ENTRYPOINT ["make"]
CMD ["frontend-check"]
