FROM python:3.9-alpine

# Needed to install 'uvloop' dependency
RUN apk add build-base

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Define port for gunicorn server
ENV PORT=8080

CMD /bin/ash -c "while true; do sleep 1000; done"
