FROM node:alpine AS deps
WORKDIR /app
COPY ./admin/package.json ./admin/yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:alpine AS builder
WORKDIR /app
COPY ./admin .
COPY --from=deps /app/node_modules ./node_modules
RUN yarn build

FROM nginx:alpine AS server
WORKDIR /usr/share/nginx/html
COPY --from=builder /app/out .
