FROM alpine:3

RUN apk add --update --no-cache\
    make\
    python3\
    gcc\
    python3-dev\
    musl-dev\
    && python3 -m ensurepip

RUN pip3 install\
    prospector\
    bandit\
    mypy\
    pytest

COPY ./backend/requirements.txt /requirements.txt

RUN pip3 install -r /requirements.txt

WORKDIR /data

ENTRYPOINT ["make"]
CMD ["--directory=./.ci", "backend-check"]
