name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci-admin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run CI for admin
        run: make --directory=./.ci ci-admin
